### ISSUE TITLE
Looking forward to Part 3

### ISSUE THREAD

**Issue by PhilipWee** [jennapederson/cloudformation-examples#2]
Hey Jenna! Thank you for all the work so far, just wanted to ask when will part 3 be out? I've been following the tutorial and I kinda need part 3 to finish my work 😅

**Comment by jennapederson** [comment]
Hey @PhilipWee! I don't have a timeline for this one yet, but I do have some code snippets. I'll see if I can pull some of that together over the next few days and update this repo. Thanks for asking and I'm glad the other parts have been helpful to you!

**Comment by PhilipWee** [comment]
That would be great! Really appreciate it
