### ISSUE TITLE
PostgreSQL supported instance classes

### ISSUE THREAD

**Issue by smlocke** [jennapederson/cloudformation-examples#3]
Hi there! I'm using your tutorials and they've been really instructive, so thank you! 

I noticed that CFN bombed out when doing the PostgreSQL tutorial (05_rds.yaml), erroring out with a message re: t2.small isn't a supported instance class. I changed it to t3.micro (a supported class, and still within free tier [I think]) and the stack created just fine.

If ... this is not the Github-friendly way of telling someone about a hiccup, I apologize! I'm rather new to all this.

**Comment by jennapederson** [comment]
@smlocke This is the best place to report this!

It looks like the default Postgres version that is installed now is 13.x, which doesn't support the db.t2.micro instance class, as you found. db.t3.micro will work, but I don't think this is part of the free tier (see [here](https://aws.amazon.com/rds/pricing/)).

If you'd like to stick with the free tier, you can set the `EngineVersion` in the template and use db.t2.micro. See [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-engineversion) for details.

Thanks for reporting this! I will get the template corrected.

**Comment by smlocke** [comment]
Ah very good, thank you! I'm honestly not sure that any free tier t2 instance classes are supported with PostgreSQL. I went to try to manually create a PostgreSQL database through the RDS console and there's no "free tier" radio button like there is with MySQL, and no t2 classes are available in any of the instance class pulldown. (I haven't actually tried the template w/ t2.micro; maybe it'll still allow it.)

The cost of t3.micro is negligible during the time it takes to execute your tutorial, absorb what you learned, and then delete the stack. It comes out to like $0.024/hour, but it's still not free as in beer. I wonder if you just can't do PostgreSQL in the free tier these days?

**Comment by jennapederson** [comment]
You should have access to use a db.t2.micro as part of the free tier with postgres, BUT it will likely depend on the postgres version. It looks like the default version installed is 13.x and it requires a t3. If you bump the postgres version (in the console or using `EngineVersion` in your CloudFormation template) down to 12.x, you can still use the db.t2 class. In the console, you can also toggle "Include previous generation classes" under DB instance class to see older generations if you need to.

**Comment by jennapederson** [comment]
Updated templates with compatible db instance class.
